pipeline {
    agent any

    tools {nodejs "NODEJS"}

    stages {
        stage('Checkout Code') {
            steps {
                echo 'Cloning repository...'
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                echo 'Installing dependencies'
                sh 'npm install'
            }
        }

        stage('Build Front-end') {
            steps {
                echo 'Building the React front-end...'
                sh 'npm run build:front'
            }
        }

        stage('Build Back-end') {
            steps {
                echo 'Building the Express back-end...'
                sh 'npm run build:back'
            }
        }

        stage('Deployment') {
            steps {
                echo 'Starting the application (front-end and back-end)...'
                sh 'npm run start'
            }
        }
    }

    post {
        success {
            archiveArtifacts artifacts: '**/build/**', fingerprint: true
            echo 'Application deployed successfully!'
        }
        failure {
            echo 'Build or deployment failed!'
        }
    }
}
