pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                echo 'Cloning repository...'
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo 'Installing dependencies'
                sh 'npm install'
                sh 'chmod -R +x node_modules/.bin'
                sh 'chmod -R +x backend/node_modules/.bin'
                sh 'chmod -R +x rag-webapp/node_modules/.bin'
                sh 'chmod +x jenkins/scripts/kill.sh'
                sh 'npm run build'
            }
        }

        stage('Deployment') {
            steps {
                echo 'Starting the application (front-end and back-end)...'
                sh 'npm run start'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }

    post {
        success {
            archiveArtifacts artifacts: '**/build/**', fingerprint: true
            echo 'Application deployed successfully!'
        }
        failure {
            echo 'Build or deployment failed!'
        }
    }
}
