pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                echo 'Cloning repository...'
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo 'Installing dependencies'
                sh 'npm install'
                sh 'chmod -R +x node_modules/.bin'
                sh 'chmod -R +x backend/node_modules/.bin'
                sh 'chmod -R +x jenkins/deployment/backend/scripts'
            }
        }

        stage('Deployment') {
            steps {
                sh './jenkins/deployment/backend/scripts/deliver.sh'
                input message: 'Finished using the api ? (Click "Proceed" to continue)'
                sh './jenkins/deployment/backend/scripts/kill.sh'
            }
        }
    }

    post {
        success {
            archiveArtifacts artifacts: '**/build/**', fingerprint: true
            echo 'Application deployed successfully!'
        }
        failure {
            echo 'Build or deployment failed!'
        }
    }
}
