pipeline {
    agent any

    tools {nodejs "NODEJS"}

    stages {
        stage('Checkout Code') {
            steps {
                echo 'Cloning repository...'
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                echo 'Installing dependencies'
                sh 'npm install'
                sh 'chmod -R +x rag-webapp/node_modules/.bin'
            }
        }

        stage('Build') {
            steps {
                echo 'Building the Express back-end...'
                sh 'npm run build:back'
            }
        }

        stage('Deployment') {
            steps {
                echo 'Starting the application (back-end)...'
                sh 'npm run start:back'
            }
        }
    }

    post {
        success {
            archiveArtifacts artifacts: '**/build/**', fingerprint: true
            echo 'Application deployed successfully!'
        }
        failure {
            echo 'Build or deployment failed!'
        }
    }
}
